name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish --no-restore
    - uses: TheDoctor0/zip-release@0.6.2
      with:
        # Filename for archive
        filename: CommonTranslate.Publish.zip
        # Working directory before zipping
        directory: bin/Debug/net6.0/
        # List of excluded files / directories
        exclusions: publish/
    - uses: actions/upload-artifact@v2
      with:
        name: CommonTranslate.Publish
        path: bin/Debug/net6.0/CommonTranslate.Publish.zip
    - name: Test
      run: dotnet test --no-build --verbosity normal
